name: Build and Push Dokcerimage to docker hub
on:
  push:
    tags:
      - '*-release'

jobs:
  buld_and_push:
    runs-on: [ubuntu-latest]

    steps:

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_LOGIN }}
        password: ${{ secrets.DOCKER_HUB_PASS }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_HUB_LOGIN }}/${{ secrets.DOCKER_HUB_REPO }}:release
  
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}