name: Build and Push Dokcerimage to docker hub
on:
  push:
    tags:
      - '*-release'

jobs:
  buld_and_push:
    runs-on: [ubuntu-latest]
    env:
      TAG_ENV: "${GITHUB_REF##*/}"

    steps:
  
    - name: Get the version v1
      id: get_version_v1
      run: echo ::set-output name=TAG::${GITHUB_REF##*/}

    - name: Get the version v2
      id: get_version_v2
      run: echo "THe tag is ${{ steps.get_version_v1.outputs.TAG }}"

    - name: Get tag only
      id: get_tag_only_v1
      run: echo  "TAG_ENV is $TAG_ENV"

    - name: Get tag only
      id: get_tag_only_v2
      run: echo  "$(echo $GITHUB_REF | cut -d / -f 3)"

    - name: Get tag only
      id: get_tag_only_v3
      run: echo  "${GITHUB_REF##*/}"

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_LOGIN }}
        password: ${{ secrets.DOCKER_HUB_PASS }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_HUB_LOGIN }}/${{ secrets.DOCKER_HUB_REPO }}:${GITHUB_REF##*/}
  
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}