name: Publish release on Docker Hub

on:
  push:
    branches:
      - '*'

jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install requirements
        run: pip install -r app/requirements.txt
             pip install pylint

      - name: Run pylint on app sources
        run: pylint --fail-under=8 app/src/* 

      - name: Run pylint on test sources
        run: pylint --fail-under=3 app/tests/* 

      - name: Run tests
        run: coverage run app/tests/tests.py

      - name: Tests report
        run: coverage report
  
  build_and_publish:
    needs: [run_tests]
    runs-on: [ubuntu-latest]
    env:
      LOGIN: ${{ secrets.DOCKER_HUB_LOGIN }}
      NAME: ${{ secrets.DOCKER_HUB_REPO }}
    steps:
      - name: Login to docker.io
        run:  echo ${{ secrets.DOCKER_HUB_PASS }} | docker login -u ${{ secrets.DOCKER_HUB_LOGIN }} --password-stdin

      - uses: actions/checkout@master

      - name: Build image
        run: docker build -t $LOGIN/$NAME:latest -f Dockerfile .

      - name: Push image to docker.io
        run: docker push $LOGIN/$NAME:latest