name: Run tests on any Push event
on:
  push:
    tags-ignore:
      - '*-release'
  pull_request:
    branches-ignore:
      - 'main'

jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install requirements
        run: pip install -r app/requirements.txt
             pip install pylint

      - name: Run pylint on app sources
        run: pylint --fail-under=8 app/src/* 

      - name: Run pylint on test sources
        run: pylint --fail-under=3 app/tests/* 

      - name: Run tests
        run: coverage run app/tests/tests.py

      - name: Tests report
        run: coverage report
          